import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, Check, Clock3, MapPin, Users } from 'lucide-react'
import { notFound } from 'next/navigation'
import { schedule } from '@/data/schedule'

const mapsUrl = 'https://www.google.com/maps/search/?api=1&query=Netaji+Subhas+University+of+Technology,+Dwarka,+New+Delhi'

const eventDetails: Record<string, { happens: string; do: string; capacity: string; format: string; forWho: string; takeaways: string[] }> = {
  'd1-1': { happens: 'The festival opens with the people and ideas that make NSUT a place for possibility. Expect a high-energy welcome, the event reveal, and a first look at what is coming across campus.', do: 'Meet fellow participants, hear from the organisers, and get oriented for the two days ahead.', capacity: 'Open to all registered attendees', format: '60-minute live ceremony', forWho: 'Students, guests, makers, and first-time visitors', takeaways: ['Know what is happening across both days', 'Find your people and your track', 'Start with the full Innovision energy'] },
  'd1-2': { happens: 'Teams bring custom-built robots into a live arena where driving skill, mechanical design, and tactical decisions matter more than a perfect prototype.', do: 'Watch the rounds, inspect the builds, and cheer for teams as they adapt under pressure.', capacity: '8 teams · up to 4 members each', format: 'Knockout arena challenge', forWho: 'Engineering students and robotics fans', takeaways: ['See real-time robot strategy', 'Learn how teams solve failures fast', 'Experience the thrill of a live build-off'] },
  'd1-3': { happens: 'Enigmata turns observation and lateral thinking into a timed puzzle run. Clues connect across rounds, so a clever hunch can change everything.', do: 'Decode prompts, connect patterns, and collaborate with your team against the clock.', capacity: 'Teams of 2–3 members', format: 'Timed puzzle challenge', forWho: 'Curious minds who enjoy riddles and logic', takeaways: ['Practice structured problem-solving', 'Build ideas from incomplete information', 'Leave with a story worth retelling'] },
  'd1-4': { happens: 'B-Plan puts a real-world problem in front of you and asks for a business that deserves to exist. Strong thinking, clear storytelling, and a viable model lead the way.', do: 'Shape an idea, define its audience, and pitch your plan to a judging panel.', capacity: 'Teams of 2–4 members', format: 'Pitch + judging round', forWho: 'Founders, strategists, and problem-solvers', takeaways: ['Turn an observation into an opportunity', 'Make your pitch sharper and shorter', 'Get a practical lens on venture building'] },
  'd1-5': { happens: 'The defence expo brings research, engineering systems, and national innovation closer to campus through exhibits and guided conversations.', do: 'Explore displays, ask questions, and understand the people and process behind complex systems.', capacity: 'Open exhibition · timed entry', format: 'Interactive expo', forWho: 'Anyone interested in aerospace, defence, and deep tech', takeaways: ['Discover emerging technologies', 'Meet people working close to the field', 'See how ideas become mission-ready systems'] },
  'd1-6': { happens: 'The Science Expo is a walk-through of student experiments that make difficult ideas visible, testable, and fun to question.', do: 'Move between exhibits, interact with demonstrations, and challenge presenters with your questions.', capacity: 'Open exhibition', format: 'Hands-on showcase', forWho: 'Learners, school visitors, and science enthusiasts', takeaways: ['Make abstract concepts tangible', 'Find projects to discuss and follow', 'See curiosity turned into a working experiment'] },
  'd1-7': { happens: 'Road Rage is an engineering sprint where speed is only one part of the equation. Control, design choices, and nerve decide who handles the course.', do: 'Watch timed runs, study the machines, and follow teams as they tune their approach.', capacity: '10 vehicles · team access', format: 'Live vehicle challenge', forWho: 'Auto enthusiasts and engineering teams', takeaways: ['See design decisions tested live', 'Understand control under pressure', 'Feel the momentum of a moving build'] },
  'd1-8': { happens: 'Felicity turns the first night into a shared campus moment with sound, lights, and performances that keep the crowd moving.', do: 'Find a good spot, meet your fellow attendees, and experience the main stage together.', capacity: 'Open to registered attendees', format: 'Live evening showcase', forWho: 'Everyone ready for a night out', takeaways: ['Discover campus talent', 'Unwind after the day’s challenges', 'Make the memory that anchors the festival'] },
  'd2-1': { happens: 'The Internship Fair brings ambitious students and teams hiring for the next generation into the same room.', do: 'Meet recruiters, ask focused questions, and make a case for the kind of work you want to do.', capacity: 'Open floor · bring your resume', format: 'Career networking fair', forWho: 'Students seeking internships and early opportunities', takeaways: ['Understand what teams actually look for', 'Make useful first introductions', 'Leave with clear next steps'] },
  'd2-2': { happens: 'A live case puts you inside a messy business decision with limited time and incomplete information. The best answer starts with the right question.', do: 'Read the case, align your team, and present a decisive recommendation.', capacity: 'Teams of 2–4 members', format: 'Case analysis + presentation', forWho: 'Analytical thinkers and future consultants', takeaways: ['Frame ambiguity with confidence', 'Prioritise insight over noise', 'Defend a recommendation clearly'] },
  'd2-3': { happens: 'ATV and auto innovators take over the expo grounds with machines, mobility ideas, and builds designed to move beyond the obvious.', do: 'Walk through the showcase, compare approaches, and speak with the teams behind each machine.', capacity: 'Open exhibition', format: 'Mobility showcase', forWho: 'Builders, drivers, and future mobility fans', takeaways: ['See practical engineering up close', 'Compare design philosophies', 'Find inspiration for your next build'] },
  'd2-4': { happens: 'These practical workshops make room for experimentation. You will move from a blank page to a rough first version with guidance along the way.', do: 'Work through a prompt, test your assumptions, and build alongside mentors and peers.', capacity: '25 seats per workshop', format: 'Hands-on guided session', forWho: 'Beginners and experienced makers', takeaways: ['Learn by doing, not watching', 'Leave with a first prototype or plan', 'Meet people who can help you keep going'] },
  'd2-5': { happens: 'Makers Showcase opens the curtain on the student projects that have been quietly taking shape across campus.', do: 'Talk to builders, ask how things work, and trace the decisions behind each finished piece.', capacity: 'Open showcase', format: 'Project demonstrations', forWho: 'Anyone looking for a next idea', takeaways: ['Learn from honest build stories', 'Find collaborators and mentors', 'See what students can make with momentum'] },
  'd2-6': { happens: 'Music, movement, and stories take the main stage in a celebration of the culture built by NSUT students.', do: 'Watch the line-up, support the performers, and share the evening with the full campus.', capacity: 'Open to registered attendees', format: 'Live cultural showcase', forWho: 'Friends, performers, and culture lovers', takeaways: ['Experience the many voices of campus', 'Discover new performers', 'End the festival on a collective high'] },
  'd2-7': { happens: 'Closing Night is the final exhale: a celebration of the teams, conversations, experiments, and unexpected moments that shaped Innovision.', do: 'Revisit your favourite moments, celebrate the people you met, and stay for the final send-off.', capacity: 'Open to registered attendees', format: 'Closing celebration', forWho: 'Every Innovision attendee', takeaways: ['Close the loop on two full days', 'Celebrate what was made together', 'Leave with a reason to come back'] },
}

export default async function EventDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const item = schedule.find((event) => event.id === id)
  if (!item) notFound()
  const detail = eventDetails[item.id] ?? eventDetails['d1-1']
  return <main className="event-detail-page">
    <div className="event-detail-nav"><Link className="logo" href="/"><span className="event-back-mark"><ArrowLeft size={16} /></span><span className="logo-text">INNOVISION<span className="logo-year">/27</span></span></Link><Link className="button button-primary" href="/#register">Register now <ArrowUpRight size={16} /></Link></div>
    <section className="event-detail-hero"><div className="event-detail-copy"><p className="eyebrow">Day {item.day} <span>—</span> {item.track}</p><h1>{item.title}</h1><p className="event-detail-lede">{item.description} {detail.happens}</p><div className="event-detail-meta"><span><Clock3 size={16} /> {item.time} IST</span><a href={mapsUrl} target="_blank" rel="noopener noreferrer"><MapPin size={16} /> {item.venue}</a></div></div><div className="event-detail-image"><img src={item.image} alt={item.title} /><span>{item.track} / Innovision 2027</span></div></section>
    <section className="event-info-grid"><div className="event-info-intro"><p className="eyebrow">Know before you join</p><h2>Come for the idea.<br /><em>Stay for the making.</em></h2></div><article className="event-info-block"><p className="eyebrow">What happens</p><p>{detail.happens}</p><p className="eyebrow info-subhead">What you&apos;ll do</p><p>{detail.do}</p></article><aside className="event-facts"><p className="eyebrow">Event facts</p><div><Users size={17} /><span><small>Capacity</small><strong>{detail.capacity}</strong></span></div><div><Clock3 size={17} /><span><small>Format</small><strong>{detail.format}</strong></span></div><div><ArrowUpRight size={17} /><span><small>For</small><strong>{detail.forWho}</strong></span></div><div className="takeaways"><small>You&apos;ll leave with</small>{detail.takeaways.map((takeaway) => <p key={takeaway}><Check size={14} /> {takeaway}</p>)}</div></aside></section>
    <section className="event-detail-bottom"><p className="eyebrow">Make your call</p><h2>Worth a<br /><em>closer look?</em></h2><div><p>Now you know what is waiting on the other side of the door. Bring your curiosity, your team, or simply an hour to explore.</p><Link className="text-link" href="/#register">Register now <ArrowUpRight size={16} /></Link><Link className="text-link" href="/#schedule">Back to schedule <ArrowLeft size={16} /></Link></div></section>
  </main>
}
